### ISSUE TITLE
Bug in Challange 2 - Particle System

### ISSUE THREAD

**Issue by gresm** [PygameCommunityDiscord/WeeklyChallenges#21]
There is a small bug in "base" version of challenge - you can shoot bullets when you are still, moving forward, rotating or moving forward and rotating clockwise, but for some reason it doesn't want to allow shooting when you are moving forward and rotating counter-clockwise.

**Comment by gresm** [comment]
As considering this issue as not important, because this challenge is finished - I am closing this issue

**Comment by ddorn** [comment]
Sorry I didn't find the time to answer this. This is actually not an issue with the code of the challenge, neither it is with pygame. It is very likely to be an issue with your keyboard. Most keyboards don't support pressing any combination of keys because, IIRC, they do now have enough wires.

You can check which combinations of key for for you there: https://keyboardchecker.com/
You can likely not make it show space, up and left pressed at the same time.
